import type { RawCoordinate } from '../types/engine';

/**
 * A lightweight proxy for CanvasRenderingContext2D.
 * Intercepts procedural Canvas API calls generated by the Director (LLM)
 * and extracts them into a sequence of discrete spatial coordinates.
 */
export class CanvasInterceptor {
  private path: RawCoordinate[] = [];
  
  // Track the pen's current position to calculate curves
  private currentX: number = 0;
  private currentY: number = 0;

  // --- No-Op State & Styling Methods ---
  public beginPath(): void {}
  public closePath(): void {}
  public stroke(): void {}
  public fill(): void {}

  // --- Core Path Generation Methods ---
  
  public moveTo(x: number, y: number): void {
    this.currentX = x;
    this.currentY = y;
    this.path.push({
      x,
      y,
      commandType: 'moveTo',
      timestamp: performance.now()
    });
  }

  public lineTo(x: number, y: number): void {
    this.currentX = x;
    this.currentY = y;
    this.path.push({
      x,
      y,
      commandType: 'lineTo',
      timestamp: performance.now()
    });
  }

  /**
   * Curve Flattening
   * Slices the cubic Bezier curve into discrete intervals (15 steps)
   * so the Kinematic Engine has continuous points to calculate velocity on.
   */
  public bezierCurveTo(cp1x: number, cp1y: number, cp2x: number, cp2y: number, x: number, y: number): void {
    const steps = 15;
    const p0x = this.currentX;
    const p0y = this.currentY;

    for (let i = 1; i <= steps; i++) {
      const t = i / steps;
      const tSq = t * t;
      const tCu = tSq * t;
      
      const invT = 1 - t;
      const invTSq = invT * invT;
      const invTCu = invTSq * invT;

      // Cubic Bezier mathematical interpolation
      const bx = invTCu * p0x + 3 * invTSq * t * cp1x + 3 * invT * tSq * cp2x + tCu * x;
      const by = invTCu * p0y + 3 * invTSq * t * cp1y + 3 * invT * tSq * cp2y + tCu * y;

      this.path.push({
        x: bx,
        y: by,
        commandType: 'bezierCurveTo',
        cp1x,
        cp1y,
        cp2x,
        cp2y,
        timestamp: performance.now()
      });
    }

    this.currentX = x;
    this.currentY = y;
  }

  /**
   * Slices a quadratic Bezier curve into discrete intervals.
   */
  public quadraticCurveTo(cpx: number, cpy: number, x: number, y: number): void {
    const steps = 15;
    const p0x = this.currentX;
    const p0y = this.currentY;

    for (let i = 1; i <= steps; i++) {
      const t = i / steps;
      const invT = 1 - t;
      
      const bx = invT * invT * p0x + 2 * invT * t * cpx + t * t * x;
      const by = invT * invT * p0y + 2 * invT * t * cpy + t * t * y;

      this.path.push({
        x: bx,
        y: by,
        commandType: 'quadraticCurveTo',
        timestamp: performance.now()
      });
    }

    this.currentX = x;
    this.currentY = y;
  }

  /**
   * Executes the LLM-generated string as Javascript code within an isolated 
   * scope where 'ctx' refers to this very CanvasInterceptor instance.
   */
  public execute(codeString: string): RawCoordinate[] {
    const previousPath = [...this.path]; // Save previous path state
    
    this.path = [];
    this.currentX = 0;
    this.currentY = 0;

    try {
      // Create a proxy to gracefully handle ANY undefined method call from the LLM
      // e.g. ctx.arc(), ctx.fillRect() instead of crashing the whole execution.
      const proxy = new Proxy(this, {
        get(target, prop) {
          if (prop in target) {
            const val = target[prop as keyof CanvasInterceptor];
            return typeof val === 'function' ? val.bind(target) : val;
          }
          return () => {}; // return a no-op function for missing methods
        },
        set(target, prop, value) {
          (target as any)[prop] = value;
          return true; // silently accept any property assignment
        }
      });

      // Using new Function creates a function with access to the global scope 
      // but we explicitly pass 'ctx' to inject our interceptor proxy.
      const evaluator = new Function('ctx', `
        "use strict";
        ${codeString}
      `);
      
      evaluator(proxy);
    } catch (error) {
      // If code is incomplete (e.g. streaming chunks), it will throw a SyntaxError.
      // We gracefully catch it, restore the previous valid path, and throw so the caller knows.
      this.path = previousPath;
      throw error;
    }

    return this.path;
  }
}
